Tidy up and rename to xcuitestrecorder

diff --git a/xcuitestrecorder b/xcuitestrecorder
--- a/xcuitestrecorder
+++ b/xcuitestrecorder
@@ -1,10 +1,16 @@
-simulator_name="iPhone 8"
-output_dir="videos"
-rm -rf $output_dir
+#!/usr/bin/env bash
+
+simulator_name=$1
+output_dir=$2
+
+if [[ -z $simulator_name || -z $output_dir ]]; then
+    echo "Required arguments are: simuator_name output_dir"
+    exit 1
+fi
 
 mkdir -p $output_dir
 while read i; do
-	if [[ "$i" =~ Test\ Case.*\[(.*)\].*started. ]]; then
+	if [[ $i =~ Test\ Case.*\[(.*)\].*started. ]]; then
 		test_name=$(echo "${BASH_REMATCH[1]}" | tr " " ".")
 		test_output_path="$output_dir/$test_name"
 		xcrun simctl io "$simulator_name" recordVideo "$test_output_path.mp4" --type "mp4" &
@@ -12,18 +18,16 @@ while read i; do
 		echo "Started to record $test_name to $test_output_path"
 	fi
 	echo "$i"
-	if [[ ! -z "$test_output_path" ]]; then
+	if [[ ! -z $test_output_path ]]; then
 		echo "$i" >> "$test_output_path.log"
 	fi
-	if [[ "$i" =~ Test\ Case.*(passed|failed).* ]]; then
+	if [[ $i =~ Test\ Case.*(passed|failed).* ]]; then
 		kill -SIGINT $pid
 		wait $pid
 		echo "Finished recording at $test_output_path"
 		if [[ ${BASH_REMATCH[1]} == "passed" ]]; then
-			rm "$test_output_path.mp4 $test_output_path.log"
+			rm "$test_output_path.mp4" "$test_output_path.log"
 		fi
 		test_output_path=""
 	fi
 done
-
-echo "Finished"
